[package]
name = "mz-auth"
description = "Shared authentication logic."
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
ring = { version = "0.17.14", features = ["std"] }
base64 = "0.22.1"
mz-ore = { path = "../ore" }
workspace-hack = { version = "0.0.0", path = "../workspace-hack", optional = true }
serde = "1.0.219"
proptest-derive = "0.5.1"
proptest = "1.6.0"
static_assertions = "1.1"

[features]
default = ["workspace-hack"]
